// ********RoostGPT********
/*
Test generated by RoostGPT for test golang-new-test using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=FormatCurrency_cc3bbdadf3
ROOST_METHOD_SIG_HASH=FormatCurrency_d831836e3e

FUNCTION_DEF=func FormatCurrency(value float64, currency string) string 
Certainly! Below are some test scenarios for the `FormatCurrency` function, which formats a given float value into a currency string using the specified currency symbol. These scenarios will cover typical usage, edge cases, and potential errors.

### Scenario 1: Format Positive Value with Default Currency Settings

Details:
- **Description**: This test checks that a positive float value is correctly formatted into a currency string with the default precision and symbol position.
- **Execution**:
  - **Arrange**: Use a positive float value and a currency symbol (e.g., "$").
  - **Act**: Call `FormatCurrency` with these parameters.
  - **Assert**: Verify that the resulting string matches the expected format (e.g., "$123.45").
- **Validation**:
  - **Explain the choice of assertion**: The assertion checks that the function appends the currency symbol and formats the number to two decimal places.
  - **Discuss the importance**: Ensures the function handles common cases of positive values, crucial for standard financial reporting.

### Scenario 2: Format Negative Value with Default Currency Settings

Details:
- **Description**: This test ensures that a negative float value is formatted properly with parentheses or a negative sign, as per the default settings.
- **Execution**:
  - **Arrange**: Use a negative float value and a currency symbol.
  - **Act**: Call `FormatCurrency` with these parameters.
  - **Assert**: Verify that the resulting string is correctly formatted (e.g., "-$123.45").
- **Validation**:
  - **Explain the choice of assertion**: The assertion checks for correct formatting of negative values.
  - **Discuss the importance**: Validates the function’s ability to distinguish and format negative numbers, which is critical for accuracy in financial applications.

### Scenario 3: Format Zero Value

Details:
- **Description**: This test verifies that a zero value is formatted correctly, using the default zero formatting.
- **Execution**:
  - **Arrange**: Use zero as the float value and a currency symbol.
  - **Act**: Call `FormatCurrency` with these parameters.
  - **Assert**: Verify that the resulting string is formatted as expected (e.g., "$0.00").
- **Validation**:
  - **Explain the choice of assertion**: Ensures zero values are handled consistently with currency formatting.
  - **Discuss the importance**: Important for clarity in reports where zero balances need to be shown clearly.

### Scenario 4: Format Large Value with Default Currency Settings

Details:
- **Description**: This test checks the function's ability to format a large float value correctly, ensuring the use of thousand separators.
- **Execution**:
  - **Arrange**: Use a large positive float value and a currency symbol.
  - **Act**: Call `FormatCurrency` with these parameters.
  - **Assert**: Verify that the resulting string includes thousand separators (e.g., "$1,234,567.89").
- **Validation**:
  - **Explain the choice of assertion**: Checks for correct insertion of thousand separators, crucial for readability of large numbers.
  - **Discuss the importance**: Ensures the function supports large financial amounts, which is essential for scalability.

### Scenario 5: Format Value with Non-standard Currency Symbol

Details:
- **Description**: This test ensures that the function can handle non-standard currency symbols correctly.
- **Execution**:
  - **Arrange**: Use a positive float value and a non-standard currency symbol (e.g., "€").
  - **Act**: Call `FormatCurrency` with these parameters.
  - **Assert**: Verify that the resulting string uses the specified symbol (e.g., "€123.45").
- **Validation**:
  - **Explain the choice of assertion**: Validates that the function can adapt to different currency symbols.
  - **Discuss the importance**: Important for internationalization and supporting multiple currencies.

### Scenario 6: Format Small Decimal Value

Details:
- **Description**: This test checks the function's rounding behavior when dealing with float values that have more than two decimal places.
- **Execution**:
  - **Arrange**: Use a float value with more than two decimal places and a currency symbol.
  - **Act**: Call `FormatCurrency` with these parameters.
  - **Assert**: Verify that the resulting string is rounded to two decimal places (e.g., "$123.46" for an input of 123.456).
- **Validation**:
  - **Explain the choice of assertion**: Ensures rounding is performed correctly according to standard financial practices.
  - **Discuss the importance**: Critical for maintaining accuracy in financial calculations and reporting.

These scenarios cover a range of common and edge cases for the `FormatCurrency` function, ensuring it behaves correctly under various conditions.
*/

// ********RoostGPT********
package currency

import (
	"testing"
	"github.com/leekchan/accounting"
)

// FormatCurrency formats the value with the given currency symbol.
func FormatCurrency(value float64, currency string) string {
	ac := accounting.Accounting{Symbol: currency, Precision: 2}
	return ac.FormatMoney(value)
}

func TestFormatCurrency(t *testing.T) {
	tests := []struct {
		name     string
		value    float64
		currency string
		expected string
	}{
		{
			name:     "Positive Value",
			value:    123.45,
			currency: "$",
			expected: "$123.45",
		},
		{
			name:     "Negative Value",
			value:    -123.45,
			currency: "$",
			expected: "-$123.45",
		},
		{
			name:     "Zero Value",
			value:    0.0,
			currency: "$",
			expected: "$0.00",
		},
		{
			name:     "Large Value",
			value:    1234567.89,
			currency: "$",
			expected: "$1,234,567.89",
		},
		{
			name:     "Non-standard Currency Symbol",
			value:    123.45,
			currency: "€",
			expected: "€123.45",
		},
		{
			name:     "Small Decimal Value",
			value:    123.456,
			currency: "$",
			expected: "$123.46",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := FormatCurrency(tt.value, tt.currency)
			if result != tt.expected {
				t.Errorf("Test %s failed: expected %s, got %s", tt.name, tt.expected, result)
			} else {
				t.Logf("Test %s succeeded: expected %s, got %s", tt.name, tt.expected, result)
			}
		})
	}
}
